# Generated by Django 6.0.4 on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_id_alter_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="colors",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="feature_1",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="product",
            name="feature_2",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="product",
            name="feature_3",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="product",
            name="feature_4",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="product",
            name="gallery_image_1",
            field=models.ImageField(blank=True, null=True, upload_to="products/gallery/"),
        ),
        migrations.AddField(
            model_name="product",
            name="gallery_image_2",
            field=models.ImageField(blank=True, null=True, upload_to="products/gallery/"),
        ),
        migrations.AddField(
            model_name="product",
            name="gallery_image_3",
            field=models.ImageField(blank=True, null=True, upload_to="products/gallery/"),
        ),
        migrations.AddField(
            model_name="product",
            name="gallery_image_4",
            field=models.ImageField(blank=True, null=True, upload_to="products/gallery/"),
        ),
    ]
